### ISSUE TITLE
Stop queries of length 1 deliver an HTML response body containing an error message

### ISSUE THREAD

**Issue by lutzthies** [kiliankoe/dvbgo#5]
`<div style="border: 3px solid #4991C5; font:1.5em; font-family:tahoma,calibri,arial; font-weight:bold; color:#1A4369; padding:5px; margin:10px; text-align:center">  The specified URL cannot be found. </div><!--0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234-->`

**Comment by lutzthies** [comment]
Let's catch this particular case by adding
```
if len(stop) <= 1 {
	return
}
```
right at the beginning of `func Monitor()` in [dvb.go](https://github.com/kiliankoe/dvbgo/blob/master/dvb.go).

**Comment by kiliankoe** [comment]
I can't seem to replicate this. Got a specific query where it doesn't work? But I guess having the guard in there can't hurt, since one letter queries are rather unreliable in any case.

**Comment by lutzthies** [comment]
Oh, you're right. I encountered this behavior after removing `lim=0` which caused #4. However, removing `ort=Dresden` as well unintentionally fixed it.

So funnily

`curl -X "GET" "http://widgets.vvo-online.de/abfahrtsmonitor/Abfahrten.do?hst=h&vz=0&ort=Dresden"`

returns 

` <div style="border: 3px solid #4991C5; font:1.5em; font-family:tahoma,calibri,arial; font-weight:bold; color:#1A4369; padding:5px; margin:10px; text-align:center">  The specified URL cannot be found. </div><!--0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234-->`

while 

`curl -X "GET" "http://widgets.vvo-online.de/abfahrtsmonitor/Abfahrten.do?hst=h&vz=0"`

returns valid departure data for a matched stop.

**Comment by kiliankoe** [comment]
Ah, I should've checked that. Interesting that everything seems buggy once an `ort` param is included... But at least this issue is fixed no matter what 😉
