### ISSUE TITLE
DVB short names for stops are misinterpreted sometimes

### ISSUE THREAD

**Issue by lutzthies** [kiliankoe/dvbgo#6]
For instance `HHZ` should return results for `Helmholtzstraße` but instead we get the ones for `Pulsnitzer Straße`.

`curl -X "GET" "http://widgets.vvo-online.de/abfahrtsmonitor/Haltestelle.do?ort=Dresden&hst=HHZ"` 
`[[["Dresden"]],[["Pulsnitzer Straße","Dresden","33000290"]]]`

Removing `ort=Dresden` from the request seems to fix the mixup.

`curl -X "GET" "http://widgets.vvo-online.de/abfahrtsmonitor/Haltestelle.do?&hst=HHZ"` `[[["Dresden"]],[["Helmholzstraße","Dresden","33000742"]]]`

**Comment by lutzthies** [comment]
Simply removing the default case
```
if city == "" {
	city = "Dresden"
}
```
should work as a fix.

**Comment by kiliankoe** [comment]
Apparently GitHub doesn't try and be smart about closing issues from commit messages 😄
